# Gloomhaven tracker app: Immutable Reference Information
# Created by: Joshua Meade
# Created on: 9/25/18

# GLOBAL CHARACTER RELATED

misc_data = {
    "random_designs": (71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95),
    "random_scenes": (63, 64, 65, 66, 67, 68, 69, 70, 71),
    "global_achieves": (("Ancient Technology", "Tech"), ("Annihilation of Order", "Unique"), ("Artifact: Cleansed", "Artifact"), ("Artifact: Lost", "Artifact"), ("Artifact: Recovered", "Artifact"), ("City Rule: Demonic", "City Rule"), ("City Rule: Economic", "City Rule"), ("City Rule: Militaristic", "City Rule"), ("End of Corruption", "Corrupt"), ("End of Gloom", "Unique"), ("End of the Invasion", "Unique"), ("The Dead Invade", "Unique"), ("The Drake Aided", "Drake"), ("The Drake Slain", "Drake"), ("The Merchant Flees", "Unique"), ("The Power of Enhancement", "Unique"), ("The Rift Neutralized", "Unique"), ("The Voice Freed", "Voice"), ("The Voice Silenced", "Voice"), ("Water-Breathing", "Unique")),
    "party_achieves": ("A Demon's Errand", "A Map to Treasure", "Across the Divide", "An Invitation", "Bad Business", "Dark Bounty", "Debt Collection", "First Steps", "Fish's Aid", "Following Clues", "Grave Job", "High Sea Escort", "Jekserah's Plans", "Redthorn's Aid", "Sin-Ra", "Stonebreaker's Censer", "The Drake's Command", "The Poison's Source", "The Scepter and the Voice", "The Voice's Command", "The Voice's Treasure", "Through the Nest", "Through the Ruins", "Through the Trench", "Tremors", "Water Staff"),
    "monster_names": ("Ancient Artillery", "Bandit Guard", "Bandit Archer", "Cave Bear", "City Guard", "City Archer", "Cultist", "Demon, Earth", "Demon, Flame", "Demon, Frost", "Demon, Night", "Demon, Sun", "Demon, Wind", "Deep Terror", "Drake, Spitting", "Drake, Vicious", "Giant Viper", "Harrower Infester", "Hound", "Imp, Black", "Imp, Forest", "Inox Guard", "Inox Archer", "Inox Shaman", "Living Bones", "Living Corpse", "Living Spirit", "Lurker", "Ooze", "Savvas Icestorm", "Savvas Lavaflow", "Stone Golem", "Vermling Scout", "Vermling Shaman"),
    "boss_names": ("Bandit Commander", "The Betrayer", "Captain of the Guard", "The Colorless", "Dark Rider", "Elder Drake", "The Gloom", "Inox Bodyguard", "Jekserah", "Merciless Overseer", "Prime Demon", "The Sightless Eye", "Winged Horror"),
    "level_up_xp": (0, 45, 95, 150, 210, 275, 345, 420, 500),
    "default_deck": ((("Crit", False, "None"), 1), (("+2", False, "None"), 1), (("+1", False, "None"), 5), (("+0", False, "None"), 6), (("-1", False, "None"), 5), (("-2", False, "None"), 1), (("Null", False, "None"), 1)),
    "reputation_mod": (5, 5, 4, 4, 4, 4, 3, 3, 3, 3, 2, 2, 2, 2, 1, 1, 1, 1, 0, 0, 0, 0, 0, -1, -1, -1, -1, -2, -2, -2, -2, -3, -3, -3, -3, -4, -4, -4, -4, -5, -5),
    "reputation_threshold": ((-1, 2), (1, 6), (5, 10), (9, 14), (13, 18), (17, 23), (22, 27), (26, 31), (30, 35), (34, 39), (38, 41)),
    # "donation_influence": (0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 13),
    "donation_landmarks": ((0, 100), (100, 150), (150, 200), (200, 250), (250, 300), (300, 350), (350, 400), (400, 500), (500, 600), (600, 700), (700, 800), (800, 900), (900, 1000), (1000, 1000^1000)),
    "prosperity_levels": ((0, 4), (4, 9), (9, 15), (15, 22), (22, 30), (30, 39), (39, 50), (50, 64))
}

misc_unlocks = {
    "Envelope_X": "[Unknown]"
}

battle_goals = {
    "Aggressor":	("Have 1+ hostile figures on the map at the beginning of every turn.", 2),
    "Diehard":	("Never allow your HP to fall below half your maximum. (Round up)", 1),
    "Dynamo":	("Kill a monster with 4+ overkill damage.", 1),
    "Executioner":	("Kill a monster at full HP with a single attack.", 1),
    "Explorer":	("Reveal a room tile by opening a door.", 1),
    "Fast Healer":	("Have full HP at end of Scene.", 1),
    "Hoarder":	("Loot 5+ money tokens.", 1),
    "Hunter":	("Kill 1+ elite monsters.", 1),
    "Indigent":	("Loot 0 money tokens.", 2),
    "Layabout":	("Gain 7- XP.", 2),
    "Masochist":	("Have 2- HP at end of Scene.", 1),
    "Neutralizer":	("Cause a trap to be sprung or disarmed on your turn or your summons' turn.", 1),
    "Opener":	("Kill the first monster.", 1),
    "Pacifist":	("Kill 3- monsters.", 1),
    "Plunderer":	("Loot a treasure overlay tile.", 1),
    "Professional":	("Use your items [Level + 2]+ times.", 1),
    "Protector":	("Allow none of your allies to die or become exhaused by HP loss.", 1),
    "Purist":	("Use no items.", 2),
    "Sadist":	("Kill 5+ monsters.", 1),
    "Scrambler":	("Take only short rests.", 1),
    "Straggler":	("Take only long rests.", 1),
    "Streamliner":	("Have 5+ cards total in Hand & Discard at end of Scene.", 1),
    "Workhorse":	("Gain 13+ XP.", 1),
    "Zealot":	("Have 3- cards total in Hand & Discard at end of Scene.", 1)
}

chest_contents = {  # Item or Scene # of -1 indicates a random option of the available remaining options.
    1:	 ("Item Design", -1),
    2:	 ("Char Item", 32),
    3:	 ("Char Item", 44),
    4:	 ("Gain Gold", 15),
    5:	 ("Char Item", 23),
    6:	 ("Char Item", 39),
    7:	 ("Side Scenario", -1),
    8:	 ("Gain Check", 1),
    9:	 ("Char Item", 111),
    10:	 ("Gain Exp", 10),
    11:	 ("Item Design", -1),
    12:	 ("Char Item", 99),
    13:	 ("Suffer Damage, POISON, & WOUND", 5),
    14:	 ("Gain Exp", 10),
    15:	 ("Char Item", 45),
    16:	 ("Gain Gold", 10),
    17:	 ("Gain Gold", 20),
    18:	 ("Gain Gold", 15),
    19:	 ("Item Design", -1),
    20:	 ("Item Design", -1),
    21:	 ("Suffer Damage", 5),
    22:	 ("Item Design", -1),
    23:	 ("Char Item", 103),
    24:	 ("Suffer Damage", 5),
    25:	 ("Gain Gold", 25),
    26:	 ("Gain Gold", 20),
    27:	 ("Char Item", 122),
    28:	 ("Gain Gold", 15),
    29:	 ("Char Item", 97),
    30:	 ("Gain Check", 1),
    31:	 ("Item Design", -1),
    32:	 ("Item Design", -1),
    33:	 ("Char Item", 19),
    34:	 ("Char Item", 24),
    35:	 ("Char Item", 98),
    36:	 ("Item Design", 96),
    37:	 ("Gain Check", 1),
    38:	 ("Item Design", 123),
    39:	 ("Suffer Damage", 5),
    40:	 ("Item Design", -1),
    41:	 ("Char Item", 53),
    42:	 ("Item Design", -1),
    43:	 ("Suffer Damage, POISON, & WOUND", 5),
    44:	 ("Side Scenario", -1),
    45:	 ("Item Design", -1),
    46:	 ("Suffer Damage & POISON", 3),
    47:	 ("Char Item", 104),
    48:	 ("Gain Gold", 30),
    49:	 ("New Scenario", 17),
    50:	 ("Char Item", 101),
    51:	 ("Side Scenario", -1),
    52:	 ("Char Item", 131),
    53:	 ("Item Design", -1),
    54:	 ("Char Item", 124),
    55:	 ("Gain Check", 1),
    56:	 ("Char Item", 69),
    57:	 ("Gain Gold", 15),
    58:	 ("Char Item", 108),
    59:	 ("Item Design", -1),
    60:	 ("Char Item", 113),
    61:	 ("Char Item", 40),
    62:	 ("Char Item", 110, 115),
    63:	 ("Item Design", -1),
    64:	 ("Gain Gold", 30),
    65:	 ("Item Design", 107),
    66:	 ("Char Item", 33),
    67:	 ("Gain Gold", 10),
    68:	 ("Char Item", 130),
    69:	 ("Char Item", 100),
    70:	 ("Side Scenario", -1),
    71:	 ("Side Scenario", -1),
    72:	 ("Char Item", 116),
    73:	 ("Item Design", -1),
    74:	 ("Item Design", -1),
    75:	 "Coded Message"
}

locations_master = {
    0:	 ("Gloomhaven", "The central city around which our adventure is set.", (8, 11, 12, 17, 18, 23, 26, 31, 35, 36, 37, 47, 50, 51, 52, 57, 58, 60, 64, 66, 70, 74, 77, 78, 83, 86, 87, 88, 89, 92, 93), None, None),
    1:	 ("Black Barrow", "Jekserah sent us here to retrieve her stolen stuff.", (2), None, (7)),
    2:	 ("Barrow Lair", "Continuation of 01-Black Barrow.", (1), ("party", "First Steps", "at least", 1), (67)),
    3:	 ("Inox Encampment", "Ransacked some of Jekserah's caravans. Murder.", None, ("global", "The Merchant Flees", "at most", 0), (65)),
    4:	 ("Crypt of the Damned", "Map found in Barrow Lair. Investigate 'Gloom.'", None, None, (38, 46)),
    5:	 ("Ruinous Crypt", "We can go fuck up some Gloom cultists.", (10), None, (4, 28)),
    6:	 ("Decaying Crypt", "Overrun cult hideout, now poses a threat to cult.", None, None, (50)),
    7:	 ("Vibrant Grotto", "Ask the Enchanter to divine Jekserah's location.", None, ("AND", ("global", "The Power of Enhancement", "at least", 1), ("global", "The Merchant Flees", "at least", 1)), None),
    8:	 ("Gloomhaven Warehouse", "Guard says Jekserah is shady AF. Proof is here.", (0), (("party", "Jekserah's Plans", "at least", 1), ("global", "The Dead Invade", "at most", 0)), (51)),
    9:	 ("Diamond Mine", "Grab a giant diamond for Jekserah. Get Paid.", None, ("global", "The Merchant Flees", "at most", 0), None),
    10:	 ("Plane of Elemental Power", "Jump through the planar rift in Ruinous Crypt.", (5, 21), ("global", "The Rift Neutralized", "at most", 0), (11)),
    11:	 ("Gloomhaven Square A", "Help Jekserah overthrow the Gloomhaven military and install a Mercantile Oligarchy", (0), ("global", "End of the Invasion", "at most", 0), (5)),
    12:	 ("Gloomhaven Square B", "Turn on Jekserah and help the city guard eliminate her threat.", (0), ("global", "End of the Invasion", "at most", 0), (34)),
    13:	 ("Temple of the Seer", "Try to dig up Jekserah's location the old fashioned way.", None, None, (10)),
    14:	 ("Frozen Hollow", "Find this damn Enchanter we keep hearing about.", None, None, (26)),
    15:	 ("Shrine of Strength", "A forgotten temple, isolated from the world, which promises great power...", None, None, None),
    16:	 ("Mountain Pass", "You've heard rumors of great flying lizards. We all know dragons don't exist, but the rumors have been too numerous to ignore...", (24), None, (1)),
    17:	 ("Lost Island", "An 'undiscovered' island in the Misty Sea, which you have been told holds great wealth.", (0), None, (71)),
    18:	 ("Abandoned Sewers", "The sewers. It seems like every adventurer ends up in a sewer, sooner or later. You may as well get your time in now.", (0), None, (63)),
    19:	 ("Forgotten Crypt", "Have Enchanter help with the rift in Ruinous Crypt.", None, ("global", "The Power of Enhancement", "at least", 1), (17)),
    20:	 ("Necromancer's Sanctum", "You have found the hiding place of the treacherous merchant woman, Jekserah. How will you approach?", None, ("global", "The Merchant Flees", "at least", 1), (60)),
    21:	 ("Infernal Throne", "Demon fucker threatened our lives...", (10), ("global", "The Rift Neutralized", "at most", 0), (15)),
    22:	 ("Temple of the Elements", "Recover 'an artifact of great power.'", None, ("OR", ("party", "A Demon's Errand", "at least", 1), ("party", "Following Clues", "at least", 1)), (21)),
    23:	 ("Deep Ruins", "[Unknown]", (0), None, (39, 72)),
    24:	 ("Echo Chamber", "[Unknown]", (16), None, (70)),
    25:	 ("Icecrag Ascent", "[Unknown]", (34), None, (58)),
    26:	 ("Ancient Cistern", "[Unknown]", (0), (("party", "Through the Ruins", "at least", 1), ("global", "Water-Breathing", "at least", 1)), (66)),
    27:	 ("Ruinous Rift", "[Unknown]", None, (("party", "Stonebreaker's Censer", "at least", 1), ("global", "Artifact: Lost", "at most", 0)), None),
    28:	 ("Outer Ritual Chamber", "[Unknown]", (29), ("party", "Dark Bounty", "at least", 1), (32)),
    29:	 ("Sanctuary of Gloom", "[Unknown]", (28), ("party", "An Invitation", "at least", 1), (41)),
    30:	 ("Shrine of the Depths", "[Unknown]", None, ("party", "The Voice's Command", "at least", 1), None),
    31:	 ("Plane of Night", "Take the corrupted artifact to the Enchanter.", (0), ("AND", ("global", "The Power of Enhancement", "at least", 1), ("global", "Artifact: Recovered", "at least", 1)), (69)),
    32:	 ("Decrepit Wood", "[Unknown]", None, ("party", "The Voice's Command", "at least", 1), None),
    33:	 ("Savvas Armory", "[Unknown]", None, ("OR", ("party", "The Voice's Command", "at least", 1), ("party, ""The Drake's Command", "at least", 1)), None),
    34:	 ("Scorched Summit", "[Unknown]", (25), (("party", "The Drake's Command", "at least", 1), ("global", "The Drake Aided", "at most", 0)), (23)),
    35:	 ("Gloomhaven Battlements A", "Give the artifact to the Prime Demon.", (0), (("party", "A Demon's Errand", "at least", 1), ("global", "The Rift Neutralized", "at most", 0)), (61)),
    36:	 ("Gloomhaven Battlements B", "Use the artifact against the Prime Demon.", (0), (("party", "A Demon's Errand", "at least", 1), ("global", "The Rift Neutralized", "at most", 0)), (2)),
    37:	 ("Doom Trench", "One of the sources drawing from the Artifact.", (0), ("global", "Water-Breathing", "at least", 1), (49)),
    38:	 ("Slave Pens", "One of the sources drawing from the Artifact.", (44), None, (29)),
    39:	 ("Treacherous Divide", "One of the sources drawing from the Artifact.", (46), None, (73)),
    40:	 ("Ancient Defense Network", "[Unknown]", (41), ("AND", ("party", "The Voice's Command", "at least", 1), ("party", "The Voice's Treasure", "at least", 1)), (47)),
    41:	 ("Timeworn Tomb", "[Unknown]", (40), ("party", "The Voice's Command", "at least", 1), (24)),
    42:	 ("Realm of the Voice", "[Unknown]", None, (("party", "The Scepter and the Voice", "at least", 1), ("global", "The Voice Freed", "at most", 0)), (30, 55)),
    43:	 ("Drake Nest", "Probably get water-breathing?", None, ("global", "The Power of Enhancement", "at least", 1), (35)),
    44:	 ("Tribal Assualt", "[Unknown]", (38), ("party", "Redthorn's Aid", "at least", 1), None),
    45:	 ("Rebel Swamp", "[Unknown]", None, ("global", "City Rule: Demonic", "at least", 1), (74)),
    46:	 ("Nightmare Peak", "[Unknown]", (39), ("party", "Across the Divide", "at least", 1), (48)),
    47:	 ("Lair of the Unseeing Eye", "[Unknown]", (0), ("party", "Through the Trench", "at least", 1), (18, 57)),
    48:	 ("Shadow Weald", "[Unknown]", None, ("party", "Redthorn's Aid", "at least", 1), (64)),
    49:	 ("Rebel's Stand", "[Unknown]", None, ("global", "City Rule: Demonic", "at least", 1), (44)),
    50:	 ("Ghost Fortress", "[Unknown]", (0), (("global", "City Rule: Demonic", "at least", 1), ("global", "Annihilation of Order", "at most", 0)), None),
    51:	 ("The Void", "[Unknown]", (0), ("global", "End of Corruption", "at least", 3), (56)),
    52:	 ("Noxious Cellar", "[Unknown]", (0), None, None),
    53:	 ("Crypt Basement", "[Unknown]", None, None, (31)),
    54:	 ("Palace of Ice", "[Unknown]", None, None, (25)),
    55:	 ("Foggy Thicket", "[Unknown]", (56), None, None),
    56:	 ("Bandit's Woods", "[Unknown]", (55), None, (45)),
    57:	 ("Investigation", "[Unknown]", (0), None, (3, 22)),
    58:	 ("Bloody Shack", "[Unknown]", (0), None, None),
    59:	 ("Forgotten Grove", "[Unknown]", None, None, None),
    60:	 ("Alchemy Lab", "[Unknown]", (0), None, None),
    61:	 ("Fading Lighthouse", "[Unknown]", (62), None, None),
    62:	 ("Pit of Souls", "[Unknown]", (61), None, (59)),
    63:	 ("Magma Pit", "[Unknown]", None, None, (12)),
    64:	 ("Underwater Lagoon", "A water stained map shows the way to an old hidden cache of... You can't quite tell. But you're certain it's worth investigating.", (0), ("global", "Water-Breathing", "at least", 1), (9)),
    65:	 ("Sulfur Mine", "An ancient map you discovered makes mention of a powerful artifact hidden away in an old sulfur mine. Perhaps it's worth investigating?", None, None, None),
    66:	 ("Clockwork Cove", "[Unknown]", (0), None, (16, 36)),
    67:	 ("Arcane Library", "[Unknown]", None, None, (14)),
    68:	 ("Toxic Moor", "[Unknown]", None, None, (33)),
    69:	 ("Well of the Unfortunate", "Investigate rumors of a 'wishing well.'", None, None, None),
    70:	 ("Chained Isle", "[Unknown]", (0), None, (6)),
    71:	 ("Windswept Highlands", "Found an old journal. Stuff for 'super potions.'", None, None, None),
    72:	 ("Oozing Grove", "[Unknown]", None, None, None),
    73:	 ("Rockslide Ridge", "[Unknown]", None, None, None),
    74:	 ("Merchant Ship", "[Unknown]", (0), ("party", "High Sea Escort", "at least", 1), (20)),
    75:	 ("Overgrown Graveyard", "[Unknown]", None, ("party", "Grave Job", "at least", 1), (53)),
    76:	 ("Harrower Hive", "Do you have the courage to face an entire brood of harrowers in their hive??", None, None, (75)),
    77:	 ("Vault of Secrets", "[Unknown]", (0), None, None),
    78:	 ("Sacrifice Pit", "[Unknown]", (0), None, None),
    79:	 ("Lost Temple", "[Unknown]", None, ("party", "Fish's Aid", "at least", 1), (52)),
    80:	 ("Vigil Keep", "[Unknown]", None, None, None),
    81:	 ("Temple of the Eclipse", "[Unknown]", None, None, (68)),
    82:	 ("Burning Mountain", "Investigate the angry fire mountain.", None, None, (62)),
    83:	 ("Shadows Within", "[Unknown]", (0), ("party", "Bad Business", "at least", 1), None),
    84:	 ("Crystalline Cave", "[Unknown]", None, ("party", "Tremors", "at least", 1), (42)),
    85:	 ("Sun Temple", "[Unknown]", None, None, None),
    86:	 ("Harried Village", "[Unknown]", (0), None, None),
    87:	 ("Corrupted Cove", "[Unknown]", (0), ("party", "The Poison's Source", "at least", 1), (40)),
    88:	 ("Plane of Water", "[Unknown]", (0), (("party", "Water Staff", "at least", 1), ("global", "Water-Breathing", "at least", 1)), (8, 37)),
    89:	 ("Syndicate Hideout", "[Unknown]", (0), ("party", "Sin-Ra", "at least", 1), (13, 27, 43)),
    90:	 ("Demonic Rift", "[Unknown]", None, None, (19)),
    91:	 ("Wild Melee", "[Unknown]", None, None, None),
    92:	 ("Back Alley Brawl", "[Unknown]", (0), ("party", "Debt Collection", "at least", 1), None),
    93:	 ("Sunken Vessel", "[Unknown]", (0), ("party", "A Map to Treasure", "at least", 1), (54)),
    94:	 ("Vermling Nest", "[Unknown]", (95), None, None),
    95:	 ("Payment Due", "[Unknown]", (94), ("party", "Through the Nest", "at least", 1), None),
}

items_master = {
    1:	("Boots of Striding", "During your movement, add +2 Move to the movement.", 2, 20, "Legs", "Spend", 0),
    2:	("Winged Shoes", "During your movement, add Jump to the movement.", 2, 20, "Legs", "Spend", 0),
    3:	("Hide Armor", "On the next two sources of damage to you from attacks, gain Shield 1.", 2, 10, "Body", "Spend", 2),
    4:	("Leather Armor", "When attacked, the attacker gains Disadvantage on the attack.", 2, 20, "Body", "Spend", 0),
    5:	("Cloak of Invisibility", "During your turn, gain INVISIBLE.", 2, 20, "Body", "Consume", 0),
    6:	("Eagle-Eye Goggles", "During your attack, gain Advantage on the entire Attack action.", 2, 30, "Head", "Spend", 0),
    7:	("Iron Helmet", "When attacked, consider any 2x attack modifier card the enemy draws to be a +0 instead.", 2, 10, "Head", "Passive", 0),
    8:	("Heater Shield", "When damaged by an attack, gain Shield 1 for the attack.", 2, 20, "One Hand", "Spend", 0),
    9:	("Piercing Bow", "During your ranged attack, ignore all Shield values for the entire Attack action.", 2, 30, "Two Hands", "Consume", 0),
    10:	("War Hammer", "During your melee attack, add STUN to the entire Attack action.", 2, 30, "Two Hands", "Consume", 0),
    11:	("Poison Dagger", "During your melee attack, add POISON to a single action.", 2, 20, "One Hand", "Spend", 0),
    12:	("Healing Potion, Minor", "During your turn, Heal 3 damage.", 4, 10, "Item", "Consume", 0),
    13:	("Stamina Potion, Minor", "During your turn, Recover up to two of your discarded cards.", 4, 10, "Item", "Consume", 0),
    14:	("Power Potion, Minor", "During your attack, add +1 Attack to your entire Attack action.", 4, 10, "Item", "Consume", 0),
    15:	("Boots of Speed", "At the beginning of a round, after all ability cards have been revealed, increase or decrease your leading initiative value by 10.", 2, 30, "Legs", "Spend", 0),
    16:	("Cloak of Pockets", "You can carry two additional small items.", 2, 20, "Body", "Passive", 0),
    17:	("Empowering Talisman", "During your turn, Refresh one of your consumed small items.", 2, 45, "Head", "Consume", 0),
    18:	("Battle-Axe", "Turn a single-target melee attack into the following: (2 adjacent hexes, both adjacent to you)", 2, 20, "One Hand", "Consume", 0),
    19:	("Weighted Net", "During your ranged attack, add IMMOBILIZE to a single attack.", 2, 20, "Two Hands", "Spend", 0),
    20:	("Mana Potion; Minor", "During your turn, create any element.", 4, 10, "Item", "Consume", 0),
    21:	("Stun Powder", "During your attack, add STUN to a single attack.", 2, 20, "Item", "Consume", 0),
    22:	("Heavy Greaves", "You are immune to all forced movement caused by enemies or scenario effects.", 2, 20, "Legs", "Passive", 1),
    23:	("Chainmail", "On the next three sources of damage to you from attacks, gain Shield 1.", 2, 20, "Body", "Spend", 3),
    24:	("Amulet of Life", "During your turn, Heal 1 damage.", 2, 20, "Head", "Spend", 0),
    25:	("Jagged Sword", "During your melee attack, add WOUND to a single attack.", 2, 30, "One Hand", "Spend", 0),
    26:	("Long Spear", "Turn a single-target melee attack into the following: (2 adjacent hexes in a line from the player)", 2, 30, "Two Hands", "Spend", 0),
    27:	("Healing Potion, Major", "During your turn, Heal 5 damage.", 4, 30, "Item", "Consume", 0),
    28:	("Moon Earring", "During your turn, Refresh all of your spent items.", 2, 20, "Item", "Consume", 0),
    29:	("Comfortable Shoes", "Whenever you use the default bottom of an ability card, perform a Move 3 action instead of a Move 2 action.", 2, 30, "Legs", "Passive", 0),
    30:	("Studded Leather", "When attacked, the attacker gains Disadvantage on the attack and you gain Shield 1 for the attack.", 2, 30, "Body", "Spend", 0),
    31:	("Hawk Helm", "During your ranged attack, add +1 Range to your entire Attack action.", 2, 20, "Head", "Spend", 0),
    32:	("Tower Shield", "When damaged by an attack, gain Shield 2 for the attack.", 2, 40, "One Hand", "Spend", 0),
    33:	("Volatile Bomb", "Turn a single-target ranged attack into the following: (3 adjacent hexes, all adjacent to each other)", 2, 30, "One Hand", "Consume", 0),
    34:	("Stamina Potion, Major", "During your turn, Recover up to three of your discarded cards.", 4, 30, "Item", "Consume", 0),
    35:	("Falcon Figurine", "Summon Jade Falcon - (HP:2, Atk:2, Mov:3, Rng:-, Flying)", 2, 50, "Item", "Consume", 0),
    36:	("Boots of Dashing", "During your movement, add +3 Move to the movement.", 2, 40, "Legs", "Spend", 0),
    37:	("Robes of Evocation", "During your attack, consume any element to add +1 Attack to the entire Attack action.", 2, 40, "Body", "Spend", 0),
    38:	("Heavy Basinet", "You are immune to STUN and MUDDLE.", 2, 30, "Head", "Passive", 2),
    39:	("Hooked Chain", "During your ranged attack, add PULL 2 to the entire Attack action.", 2, 40, "Two Hands", "Spend", 0),
    40:	("Versatile Dagger", "Whenever you use the default top of an ability card, perform an Attack 3 action instead of an Attack 2 action.", 2, 25, "One Hand", "Passive", 0),
    41:	("Power Potion, Major", "During your attack, add +2 Attack to your entire Attack action.", 4, 40, "Item", "Consume", 0),
    42:	("Ring of Haste", "At the end of your turn, play one card from your hand and immediately perform the bottom action of the card.", 2, 30, "Item", "Consume", 0),
    43:	("Boots of Quickness", "At the beginning of a round, after all ability cards have been revealed, increase or decrease your leading initiative value by 20.", 2, 75, "Legs", "Spend", 0),
    44:	("Splintmail", "On the next four sources of damage to you from attacks, gain Shield 1.", 2, 35, "Body", "Spend", 4),
    45:	("Pendant of Dark Pacts", "During your turn, Refresh two of your consumed small items. Gain CURSE.", 2, 75, "Head", "Consume", 0),
    46:	("Spiked Shield", "When damaged by an attack, gain Shield 1 and Retaliate 2 for the attack.", 2, 40, "One Hand", "Spend", 0),
    47:	("Reaping Scythe", "Turn a single-target melee attack into the following: (3 hexes, all adjacent to the player, and two of which are adjacent to the middle target.)", 2, 40, "Two Hands", "Consume", 0),
    48:	("Mana Potion; Major", "During your turn, create any two elements.", 4, 30, "Item", "Consume", 0),
    49:	("Sun Earring", "During your turn, Refresh all of your spent items and Heal 3 damage.", 2, 40, "Item", "Consume", 0),
    50:	("Steel Sabatons", "If you move 1 or fewer hexes on your turn, gain Shield 1 for the round.", 2, 60, "Legs", "Passive", 2),
    51:	("Shadow Armor", "When you are damaged by an attack, suffer no damage instead.", 2, 30, "Body", "Consume", 0),
    52:	("Protective Charm", "You are immune to POISON and WOUND.", 2, 60, "Head", "Passive", 0),
    53:	("Black Knife", "During your melee attack, add CURSE to a single attack.", 2, 25, "One Hand", "Spend", 0),
    54:	("Staff of Eminence", "During your ranged attack, consume any element to add +1 Attack to the entire Attack action.", 2, 60, "Two Hands", "Spend", 0),
    55:	("Healing Potion, Super", "During your turn, Heal 7 damage.", 4, 50, "Item", "Consume", 0),
    56:	("Ring of Brutality", "At the end of your turn, play one card from your hand and immediately perform the top action of the card.", 2, 40, "Item", "Consume", 0),
    57:	("Serene Sandals", "Whenever you use the default bottom of an ability card perform a Move 4 action instead of a Move 2 action.", 2, 75, "Legs", "Passive", 0),
    58:	("Cloak of Phasing", "Gain flying. While occupying an obstacle hex, you are considered Invisible and cannot attack.", 2, 75, "Body", "Passive", 0),
    59:	("Telescopic Lens", "During your ranged attack, add +2 Range to your entire Attack action.", 2, 50, "Head", "Spend", 0),
    60:	("Unstable Explosives", "Turn a single target ranged attack into the following: (4 hex attack, 2 above and 2 below in a parallelogram). All allies in the attack area suffer 3 damage.", 2, 45, "One Hand", "Consume", 0),
    61:	("Wall Shield", "When damaged by an attack, gain Shield 4 for the attack.", 2, 60, "Two Hands", "Spend", 0),
    62:	("Doom Powder", "During your attack, add Stun, Poison, and Curse to a single attack.", 2, 40, "Item", "Consume", 0),
    63:	("Lucky Eye", "During your turn, Strengthen yourself and all adjacent allies.", 2, 60, "Item", "Consume", 0),
    64:	("Boots of Sprinting", "During your movement, add +4 Move to the movement.", 2, 75, "Legs", "Spend", 0),
    65:	("Platemail", "On the next five sources of damage to you from attacks, gain Shield 1.", 2, 50, "Body", "Spend", 5),
    66:	("Mask of Terror", "During your melee attack, add Push 1.", 2, 50, "Head", "Passive", 0),
    67:	("Balanced Blade", "Whenever you use the default top of an ability card, perform an Attack 4 instead of an Attack 2 action.", 2, 60, "One Hand", "Passive", 0),
    68:	("Halberd", "During your single target melee attack, you can attack any single enemy within 2 hexes.", 2, 75, "Two Hands", "Passive", 0),
    69:	("Star Earring", "During your turn, Refresh all of your spent items, Heal 3 damage, and Recover up to two of your discarded cards.", 2, 70, "Item", "Consume", 0),
    70:	("Second Chance Ring", "At the end of your turn, play two cards from your hand and perform an additional turn this round based on your new leading initiative (which must be later than your previous initiative).", 2, 75, "Item", "Consume", 0),
    71:	("Boots of Levitation", "Gain Flying.", 2, 50, "Legs", "Passive", 0),
    72:	("Shoes of Happiness", "If you move 6 or more hexes on your turn, gain 1 experience.", 2, 50, "Legs", "Passive", 0),
    73:	("Blinking Cape", "During your turn, perform a 'Move 4, Jump' action", 2, 50, "Body", "Consume", 0),
    74:	("Swordedge Armor", "On the next three sources of damage from attacks targeting you, gain Shield 1, Retaliate 1", 2, 40, "Body", "Spend", 4),
    75:	("Circlet of Elements", "During your turn, consume any element to create any element", 2, 25, "Head", "Spend", 0),
    76:	("Chain Hood", "While you are adjacent to three or more monsters, gain Shield 1", 2, 40, "Head", "Passive", 1),
    77:	("Frigid Blade", "During your melee attack, consume Ice to add +2 Attack to a single attack.", 2, 30, "One Hand", "Passive", 0),
    78:	("Storm Blade", "During your melee attack, consume Wind to add +2 Attack to a single attack.", 2, 30, "One Hand", "Passive", 0),
    79:	("Inferno Blade", "During your melee attack, consume Fire to add +2 Attack to a single attack.", 2, 30, "One Hand", "Passive", 0),
    80:	("Tremor Blade", "During your melee attack, consume Earth to add +2 Attack to a single attack.", 2, 30, "One Hand", "Passive", 0),
    81:	("Brilliant Blade", "During your melee attack, consume Light to add +2 Attack to a single attack.", 2, 30, "One Hand", "Passive", 0),
    82:	("Night Blade", "During your melee attack, consume Dark to add +2 Attack to a single attack.", 2, 30, "One Hand", "Passive", 0),
    83:	("Wand of Frost", "During your turn, create Ice.", 2, 30, "One Hand", "Spend", 0),
    84:	("Wand of Storms", "During your turn, create Air.", 2, 30, "One Hand", "Spend", 0),
    85:	("Wand of Infernos", "During your turn, create Fire.", 2, 30, "One Hand", "Spend", 0),
    86:	("Wand of Tremors", "During your turn, create Earth.", 2, 30, "One Hand", "Spend", 0),
    87:	("Wand of Brilliance", "During your turn, create Light.", 2, 30, "One Hand", "Spend", 0),
    88:	("Wand of Darkness", "During your turn, create Dark.", 2, 30, "One Hand", "Spend", 0),
    89:	("Minor Cure Potion", "During your turn, remove one negative condition on yourself. This can be used while you have Stun.", 2, 10, "Item", "Consume", 0),
    90:	("Major Cure Potion", "During your turn, remove all negative conditions on yourself. This can be used while you have Stun.", 2, 30, "Item", "Consume", 0),
    91:	("Steel Ring", "When damaged by an attack targeting you, gain Shield 4 for the attack.", 2, 20, "Item", "Consume", 0),
    92:	("Dampening Ring", "Before an enemy would consume an element, consume that element instead for no effect", 2, 25, "Item", "Consume", 0),
    93:	("Scroll of Power", "During an ally's attack, add +1 Attack to their entire attack action", 2, 30, "Item", "Consume", 0),
    94:	("Scroll of Healing", "During your turn, perform a 'Heal 3, Range 5' action", 2, 30, "Item", "Consume", 0),
    95:	("Scroll of Stamina", "During your turn, an ally within Range 5 may recover up to two of their discarded cards", 2, 50, "Item", "Consume", 0),
    96:	("Rocket Boots", "During your movement, add +3 Move and Jump to a single movement", 2, 8, "Legs", "Spend", 0),
    97:	("Endurance Footwraps", "If you move 4 or more hexes on your turn, perform a 'Heal 1, Self' action.", 1, 40, "Legs", "Passive", 0),
    98:	("Drakescale Boots", "You are unaffected by difficult and hazardous terrain.", 1, 50, "Legs", "Passive", 0),
    99:	("Magma Waders", "Ignore the damaging effects of hazardous terrain and perform a 'Heal 2, Self' action on any turn in which you have entered a hazardous terrain hex.", 1, 50, "Legs", "Passive", 0),
    100:	("Robes of Summoning", "During your turn, perform a 'Heal 2, target any summoned ally' action.", 1, 40, "Body", "Spend", 0),
    101:	("Second Skin", "Remove two -1 from your attack modifier deck.", 1, 30, "Body", "Passive", 0),
    102:	("Sacrificial Robes", "During your ranged attack, suffer 3 damage to add +1 Attack to the entire Attack action.", 1, 50, "Body", "Consume", 0),
    103:	("Drakescale Armor", "You are immune to Poison and Wound.", 1, 50, "Body", "Passive", 0),
    104:	("Steam Armor", "On the next five sources of damage from attacks targeting you, gain Shield 1.", 1, 50, "Body", "Consume", 0),
    105:	("Flea-Bitten Shawl", "You are considered to have an initiative of 99 for the purpose of enemy focusing.", 1, 10, "Body", "Passive", 0),
    106:	("Necklace of Teeth", "Any time you kill an enemy during your turn, perform a 'Heal 1, Self' action.", 1, 40, "Head", "Passive", 0),
    107:	("Horned Helm", "After moving 4 or more hexes on your turn, add +1 Attack to your next melee attack this turn.", 2, 30, "Head", "Passive", 0),
    108:	("Drakescale Helm", "Whenever you gain Muddle, gain Strengthen instead.", 1, 50, "Head", "Passive", 0),
    109:	("Thief's Hood", "During your 'Loot 1' ability, perform a 'Loot 2' ability instead.", 1, 20, "Head", "Consume", 0),
    110:	("Helm of the Mountain", "When attacked, if Earth is Strong, Immobilize the attacker.", 1, 50, "Head", "Passive", 0),
    111:	("Wave Crest", "When attacked, if Ice is Strong, perform a 'Push 2' action targeting the attacker.", 1, 50, "Head", "Passive", 0),
    112:	("Ancient Drill", "During your melee attack, add +2 Attack and Pierce 2 to the entire Attack action", 2, 30, "Two Hands", "Consume", 0),
    113:	("Skullbane Axe", "During your melee attack targeting a Living Corpse, Living Spirit, or Living Bones, add +5 Attack to a single attack.", 1, 50, "Two Hands", "Spend", 0),
    114:	("Staff of Xorn", "During your ranged attack, add Poison and Muddle to the entire Attack action", 1, 50, "Two Hands", "Consume", 0),
    115:	("Mountain Hammer", "Summon Warrior Spirit - (HP:4, Atk:3, Mov:1, Rng:-)", 1, 50, "Two Hands", "Consume", 0),
    116:	("Fueled Falchion", "During your single-target melee attack, the target and all enemies adjacent to the target suffer 1 damage", 2, 20, "One Hand", "Consume", 0),
    117:	("Bloody Axe", "During your melee attack, suffer 2 damage to add +1 Attack to the entire Attack action.", 2, 40, "One Hand", "Spend", 0),
    118:	("Staff of Elements", "During your turn, create any element.", 2, 50, "Two Hands", "Spend", 0),
    119:	("Skull of Hatred", "During your turn, Curse all adjacent enemies.", 1, 50, "One Hand", "Consume", 0),
    120:	("Staff of Summoning", "During your turn, a summoned ally within Range 3 performs a 'Move 3' action with you controlling the action.", 1, 60, "Two Hands", "Spend", 0),
    121:	("Orb of Dawn", "During your turn, use Dark to create Light.", 1, 50, "One Hand", "Passive", 0),
    122:	("Orb of Twilight", "During your turn, use Light to create Dark.", 1, 50, "One Hand", "Passive", 0),
    123:	("Ring of Skulls", "Summon Skeleton - (HP:3, Atk:2, Mov:2, Rng:-)", 2, 50, "Item", "Consume", 0),
    124:	("Doomed Compass", "During your turn, force an enemy within Range 5 to perform a 'Move 2' action with you controlling the action.", 1, 50, "Item", "Consume", 0),
    125:	("Curious Gear", "During your turn, disarm all traps within Range 2.", 1, 50, "Item", "Consume", 0),
    126:	("Remote Spider", "During your turn, Poison all adjacent enemies.", 1, 40, "Item", "Consume", 0),
    127:	("Giant Remote Spider", "During your turn, perform a 'Loot 1' action.", 1, 60, "Item", "Consume", 0),
    128:	("Black Censer", "During your turn, Muddle all enemies with Range 2.", 1, 50, "Item", "Consume", 0),
    129:	("Black Card", "During your turn, place a character token on an adjacent normal or elite enemy. You add +1 Attack to all your attacks targeting this enemy.", 1, 75, "Item", "Consume", 0),
    130:	("Helix Ring", "During your turn, use light and dark to perform a 'Heal 25, Self' action", 1, 50, "Item", "Consume", 0),
    131:	("Heart of the Betrayer", "When attacked by an adjacent normal enemy, force the enemy to attack one of its allies within its range instead.", 1, 60, "Item", "Consume", 0),
    132:	("Power Core", "Summon Steel Construct - (HP:5, Atk:3, Mov:2, Rng:-)", 1, 75, "Item", "Consume", 0),
    133:	("Resonant Crystal", "During your turn, destroy an adjacent obstacle.", 1, 20, "Item", "Consume", 0),
    134:	("Imposing Blade", "Any time you kill an enemy during your turn, gain Shield 1 for the rest of the round.", 1, 50, "One Hand", "Passive", 0),
    135:	("Focusing Ray", "During your Heal action, double the value of the Heal.", 1, 50, "One Hand", "Consume", 0),
    136:	("Volatile Elixer", "During your ranged attack, add +2 Attack and gain Advantage on the entire Attack action, but suffer 2 damage for each attack made.", 1, 50, "Item", "Consume", 0),
    137:	("Silent Stiletto", "Whenever you make a single-target melee attack, add Pierce 1.", 1, 50, "One Hand", "Passive", 0),
    138:	("Stone Charm", "During your action where an obstacle is created, create one additional obstacle and apply all effects of the action to it.", 1, 50, "Head", "Spend", 0),
    139:	("Psychic Knife", "Any time you perform an Augment action, add +1 Attack to the entire action.", 1, 50, "One Hand", "Passive", 0),
    140:	("Sun Shield", "When damaged by an attack, you may consume Light to gain Shield 3 for the attack.", 1, 50, "One Hand", "Passive", 0),
    141:	("Utility Belt", "During your turn, you or any one ally may Refresh one of your spent or consumed items.", 1, 50, "Item", "Consume", 0),
    142:	("Phasing Idol", "When a summon you own is damaged by an attack, it suffers no damage instead.", 1, 50, "Item", "Consume", 0),
    143:	("Smoke Elixer", "During your turn, gain INVISIBLE and create Dark.", 1, 50, "Item", "Consume", 0),
    144:	("Pendant of the Plague", "During your turn, POISON and CURSE one enemy within Range 3.", 1, 50, "Head", "Spend", 0),
    145:	("Mask of Death", "Any time you perform a melee attack and you have exactly 1 hit point, add +2 Attack to the Attack.", 1, 50, "Head", "Passive", 0),
    146:	("Master's Lute", "After performing any song action, immediately perform an Attack 2 or Move 2 action.", 1, 50, "Two Hands", "Passive", 0),
    147:	("Cloak of the Hunter", "Any time you perform a Doom action, MUDDLE the target of the Doom.", 1, 50, "Body", "Passive", 0),
    148:	("Doctor's Coat", "Any time an ally performs a Medical Pack or Large Medical Pack action, they add +1 Heal to their Heal.", 1, 50, "Body", "Passive", 0),
    149:	("Elemental Boots", "If you move 5 or more hexes on your turn, create any element.", 1, 50, "Legs", "Passive", 0),
    150:	("Staff of Command", "After performing a Command action, play one card from your hand and immediately perform the same side of the card (top or bottom) as the Command action.", 1, 50, "Two Hands", "Spend", 0),
}

perks_trispike = {
    1:	 ("Remove two -1 cards.", (("-1", False, "None"), -2), False, False),
    2:	 ("Replace one -1 card with one +1 card.", ((("-1", False, "None"), -1), (("+1", False, "None"), 1)), False, False),
    3:	 ("Add two +1 cards.", (("+1", False, "None"), 2), False, False),
    4:	 ("Add two +1 cards.", (("+1", False, "None"), 2), False, False),
    5:	 ("Add one +3 card.", (("+3", False, "None"), 1), False, False),
    6:	 ("Add three [rolling] Push 1 cards.", (("+0", True, "Push 1"), 3), False, False),
    7:	 ("Add three [rolling] Push 1 cards.", (("+0", True, "Push 1"), 3), False, False),
    8:	 ("Add two [rolling] Pierce 3 cards.", (("+0", True, "Pierce 3"), 2), False, False),
    9:	 ("Add one [rolling] Stun card.", (("+0", True, "Stun"), 1), False, False),
    10:	 ("Add one [rolling] Stun card.", (("+0", True, "Stun"), 1), False, False),
    11:	 ("Add one [rolling] Disarm card & add one [rolling] Muddle card.", ((("+0", True, "Disarm"), 1), (("+0", True, "Muddle"), 1)), False, False),
    12:	 ("Add one [rolling] Add Target card.", (("+0", True, "Add Target 1"), 1), False, False),
    13:	 ("Add one [rolling] Add Target card.", (("+0", True, "Add Target 1"), 1), False, False),
    14:	 ("Add one +1; Shield 1 Self card.", (("+1", False, "Shield 1"), 1), False, False),
    15:	 ("Ignore negative item effects & add one +1 card.", (("+1", False, "None"), 1), True, False)
}

perks_gear = {
    1:	 ("Remove two -1 cards", (("-1", False, "None"), -2), False, False),
    2:	 ("Remove two -1 cards", (("-1", False, "None"), -2), False, False),
    3:	 ("Replace one -2 card with one +0 card", ((("-2", False, "None"), -1), (("+0", False, "None"), 1)), False, False),
    4:	 ("Add two +1 cards", (("+1", False, "None"), 2), False, False),
    5:	 ("Add one +3 card", (("+3", False, "None"), 1), False, False),
    6:	 ("Add two [rolling] Flame cards", (("+0", True, "Flame"), 2), False, False),
    7:	 ("Add three [rolling] Muddle cards", (("+0", True, "Muddle"), 3), False, False),
    8:	 ("Add one +1 Wound card", (("+1", False, "Wound"), 1), False, False),
    9:	 ("Add one +1 Wound card", (("+1", False, "Wound"), 1), False, False),
    10:	 ("Add one +1 Immobilize card", (("+1", False, "Immobilize"), 1), False, False),
    11:	 ("Add one +1 Immobilize card", (("+1", False, "Immobilize"), 1), False, False),
    12:	 ("Add one +1 Heal 2 card", (("+1", False, "Heal 2"), 1), False, False),
    13:	 ("Add one +1 Heal 2 card", (("+1", False, "Heal 2"), 1), False, False),
    14:	 ("Add one +0 Add Target card", (("+0", False, "Add Target 1"), 1), False, False),
    15:	 ("Ignore negative scenario effects", (("+0", False, "None"), 0), False, True),
}

perks_star = {
    1:	 ("Remove four +0 cards", (("+0", False, "None"), -4), False, False),
    2:	 ("Replace one -1 card with one +1 card", ((("-1", False, "None"), -1), (("+1", False, "None"), 1)), False, False),
    3:	 ("Replace one -1 card with one +1 card", ((("-1", False, "None"), -1), (("+1", False, "None"), 1)), False, False),
    4:	 ("Add two +1 cards", (("+1", False, "None"), 2), False, False),
    5:	 ("Add two +1 cards", (("+1", False, "None"), 2), False, False),
    6:	 ("Add one +0 Stun card", (("+1", False, "Stun"), 1), False, False),
    7:	 ("Add one +1 Wound card", (("+1", False, "Wound"), 1), False, False),
    8:	 ("Add one +1 Immobilize card", (("+1", False, "Immobilize"), 1), False, False),
    9:	 ("Add one +1 Curse card", (("+1", False, "Curse"), 1), False, False),
    10:	 ("Add one +2 Flame card", (("+2", False, "Flame"), 1), False, False),
    11:	 ("Add one +2 Flame card", (("+2", False, "Flame"), 1), False, False),
    12:	 ("Add one +2 Frost card", (("+2", False, "Frost"), 1), False, False),
    13:	 ("Add one +2 Frost card", (("+2", False, "Frost"), 1), False, False),
    14:	 ("Add one [rolling] Earth card & add one [rolling] Air card", ((("+0", True, "Earth"), 1), (("+0", True, "Air"), 1)), False, False),
    15:	 ("Add one [rolling] Shadow card & add one [rolling] Light card", ((("+0", True, "Shadow"), 1), (("+0", True, "Light"), 1)), False, False),
}

perks_daggers = {
    1:	 ("Remove two -1 cards", (("-1", False, "None"), -2), False, False),
    2:	 ("Remove two -1 cards", (("-1", False, "None"), -2), False, False),
    3:	 ("Remove four +0 cards", (("+0", False, "None"), -4), False, False),
    4:	 ("Replace one -2 card with one +0 card", ((("-2", False, "None"), -1), (("+0", False, "None"), 1)), False, False),
    5:	 ("Replace one -1 card with one +1 card", ((("-1", False, "None"), -1), (("+1", False, "None"), 1)), False, False),
    6:	 ("Replace one +0 card with one +2 card", ((("+0", False, "None"), -1), (("+2", False, "None"), 1)), False, False),
    7:	 ("Replace one +0 card with one +2 card", ((("+0", False, "None"), -1), (("+2", False, "None"), 1)), False, False),
    8:	 ("Add two [rolling] +1 cards", (("+1", True, "None"), 2), False, False),
    9:	 ("Add two [rolling] +1 cards", (("+1", True, "None"), 2), False, False),
    10:	 ("Add two [rolling] Pierce 3 cards", (("+0", True, "Pierce 3"), 2), False, False),
    11:	 ("Add two [rolling] Poison cards", (("+0", True, "Poison"), 2), False, False),
    12:	 ("Add two [rolling] Poison cards", (("+0", True, "Poison"), 2), False, False),
    13:	 ("Add two [rolling] Muddle cards", (("+0", True, "Muddle"), 2), False, False),
    14:	 ("Add one [rolling] Invisible card", (("+0", True, "Invisibility"), 1), False, False),
    15:	 ("Ignore negative scenario effects", (("+0", False, "None"), 0), False, True),
}

perks_shatter = {
    1:	 ("Remove four +0 cards.", (("+0", False, "None"), -4), False, False),
    2:	 ("Replace one -1 card with one +1 card.", ((("-1", False, "None"), -1), (("+1", False, "None"), 1)), False, False),
    3:	 ("Replace one -1 card with one +1 card.", ((("-1", False, "None"), -1), (("+1", False, "None"), 1)), False, False),
    4:	 ("Replace one -1 card with one +1 card.", ((("-1", False, "None"), -1), (("+1", False, "None"), 1)), False, False),
    5:	 ("Add one -2 card & add two +2 cards.", ((("-2", False, "None"), 1), (("+2", False, "None"), 2)), False, False),
    6:	 ("Add one +1 Immobilize card.", (("+1", False, "Immobilize"), 1), False, False),
    7:	 ("Add one +1 Immobilize card.", (("+1", False, "Immobilize"), 1), False, False),
    8:	 ("Add one +2 Muddle card.", (("+2", False, "Muddle"), 1), False, False),
    9:	 ("Add one +2 Muddle card.", (("+2", False, "Muddle"), 1), False, False),
    10:	 ("Add two [rolling] Push 2 cards.", (("+0", True, "Push 2"), 2), False, False),
    11:	 ("Add two [rolling] Earth cards.", (("+0", True, "Earth"), 2), False, False),
    12:	 ("Add two [rolling] Earth cards.", (("+0", True, "Earth"), 2), False, False),
    13:	 ("Add two [rolling] Air cards.", (("+0", True, "Air"), 2), False, False),
    14:	 ("Ignore negative item effects.", (("+0", False, "None"), 0), True, False),
    15:	 ("Ignore negative scenario effects.", (("+0", False, "None"), 0), False, True),
}

perks_brain = {
    1:	 ("Remove four +0 cards.", (("+0", False, "None"), -4), False, False),
    2:	 ("Replace one -1 card with one +1 card.", ((("-1", False, "None"), -1), (("+1", False, "None"), 1)), False, False),
    3:	 ("Replace one -1 card with one +1 card.", ((("-1", False, "None"), -1), (("+1", False, "None"), 1)), False, False),
    4:	 ("Replace one -1 card with one +1 card.", ((("-1", False, "None"), -1), (("+1", False, "None"), 1)), False, False),
    5:	 ("Add one -2 card & add two +2 cards.", ((("-2", False, "None"), 1), (("+2", False, "None"), 2)), False, False),
    6:	 ("Add one +1 Immobilize card.", (("+1", False, "Immobilize"), 1), False, False),
    7:	 ("Add one +1 Immobilize card.", (("+1", False, "Immobilize"), 1), False, False),
    8:	 ("Add one +2 Muddle card.", (("+2", False, "Muddle"), 1), False, False),
    9:	 ("Add one +2 Muddle card.", (("+2", False, "Muddle"), 1), False, False),
    10:	 ("Add two [rolling] Push 2 cards.", (("+0", True, "Push 2"), 2), False, False),
    11:	 ("Add two [rolling] Earth cards.", (("+0", True, "Earth"), 2), False, False),
    12:	 ("Add two [rolling] Earth cards.", (("+0", True, "Earth"), 2), False, False),
    13:	 ("Add two [rolling] Air cards.", (("+0", True, "Air"), 2), False, False),
    14:	 ("Ignore negative item effects.", (("+0", False, "None"), 0), True, False),
    15:	 ("Ignore negative scenario effects.", (("+0", False, "None"), 0), False, True),
}

perks_sun = {
    1:	 ("Remove two -1 cards", (("-1", False, "None"), -2), False, False),
    2:	 ("Remove two -1 cards", (("-1", False, "None"), -2), False, False),
    3:	 ("Remove four +0 cards", (("+0", False, "None"), -4), False, False),
    4:	 ("Replace one -2 card with one +0 card", ((("-2", False, "None"), -1), (("+0", False, "None"), 1)), False, False),
    5:	 ("Replace one +0 card with one +2 card", ((("+0", False, "None"), -1), (("+2", False, "None"), 1)), False, False),
    6:	 ("Add two [rolling] +1 cards", (("+1", True, "None"), 2), False, False),
    7:	 ("Add two [rolling] +1 cards", (("+1", True, "None"), 2), False, False),
    8:	 ("Add two [rolling] Heal 1 cards", (("+0", True, "Heal 1"), 2), False, False),
    9:	 ("Add two [rolling] Heal 1 cards", (("+0", True, "Heal 1"), 2), False, False),
    10:	 ("Add one [rolling] Stun card", (("+0", True, "Stun"), 1), False, False),
    11:	 ("Add two [rolling] Light cards.", (("+0", True, "Light"), 2), False, False),
    12:	 ("Add two [rolling] Light cards.", (("+0", True, "Light"), 2), False, False),
    13:	 ("Add two [rolling] Shield 1 Self cards.", (("+0", True, "Shield 1"), 2), False, False),
    14:	 ("Ignore negative item effects & add two +1 cards", (("+1", False, "None"), 2), True, False),
    15:	 ("Ignore negative scenario effects", (("+0", False, "None"), 0), False, True),
}

perks_spears = {
    1:	 ("Remove two -1 cards", (("-1", False, "None"), -2), False, False),
    2:	 ("Remove two -1 cards", (("-1", False, "None"), -2), False, False),
    3:	 ("Remove four +0 cards", (("+0", False, "None"), -4), False, False),
    4:	 ("Replace one +0 card with one +2 card", ((("+0", False, "None"), -1), (("+2", False, "None"), 1)), False, False),
    5:	 ("Replace one +0 card with one +2 card", ((("+0", False, "None"), -1), (("+2", False, "None"), 1)), False, False),
    6:	 ("Add two [rolling] +1 cards", (("+1", True, "None"), 2), False, False),
    7:	 ("Add two [rolling] +1 cards", (("+1", True, "None"), 2), False, False),
    8:	 ("Add three [rolling] muddle cards", (("+0", True, "Muddle"), 3), False, False),
    9:	 ("Add two [rolling] Pierce 3 cards", (("+0", True, "Pierce 3"), 2), False, False),
    10:	 ("Add one [rolling] Stun card", (("+0", True, "Stun"), 1), False, False),
    11:	 ("Add one [rolling] Add Target card", (("+0", True, "Add Target"), 1), False, False),
    12:	 ("Add one +0 Refresh an item card", (("+0", False, "Refresh Item"), 1), False, False),
    13:	 ("Add one +0 Refresh an item card", (("+0", False, "Refresh Item"), 1), False, False),
    14:	 ("Add one +0 Refresh an item card", (("+0", False, "Refresh Item"), 1), False, False),
    15:	 ("Ignore negative item effects & add two +1 cards", (("+1", False, "None"), 2), True, False),
}

perks_circles = {
    1:	 ("Remove two -1 cards", (("-1", False, "None"), -2), False, False),
    2:	 ("Remove two -1 cards", (("-1", False, "None"), -2), False, False),
    3:	 ("Remove four +0 cards", (("+0", False, "None"), -4), False, False),
    4:	 ("Replace one +0 card with one +2 card", ((("+0", False, "None"), -1), (("+2", False, "None"), 1)), False, False),
    5:	 ("Replace one +0 card with one +2 card", ((("+0", False, "None"), -1), (("+2", False, "None"), 1)), False, False),
    6:	 ("Add two [rolling] +1 cards", (("+1", True, "None"), 2), False, False),
    7:	 ("Add two [rolling] +1 cards", (("+1", True, "None"), 2), False, False),
    8:	 ("Add three [rolling] muddle cards", (("+0", True, "Muddle"), 3), False, False),
    9:	 ("Add two [rolling] Pierce 3 cards", (("+0", True, "Pierce 3"), 2), False, False),
    10:	 ("Add one [rolling] Stun card", (("+0", True, "Stun"), 1), False, False),
    11:	 ("Add one [rolling] Add Target card", (("+0", True, "Add Target"), 1), False, False),
    12:	 ("Add one +0 Refresh an item card", (("+0", False, "Refresh Item"), 1), False, False),
    13:	 ("Add one +0 Refresh an item card", (("+0", False, "Refresh Item"), 1), False, False),
    14:	 ("Add one +0 Refresh an item card", (("+0", False, "Refresh Item"), 1), False, False),
    15:	 ("Ignore negative item effects & add two +1 cards", (("+1", False, "None"), 2), True, False),
}

perks_eclipse = {
    1:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    2:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    3:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    4:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    5:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    6:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    7:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    8:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    9:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    10:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    11:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    12:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    13:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    14:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    15:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
}

perks_cthulu = {
    1:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    2:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    3:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    4:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    5:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    6:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    7:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    8:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    9:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    10:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    11:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    12:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    13:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    14:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    15:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
}

perks_lightning = {
    1:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    2:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    3:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    4:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    5:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    6:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    7:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    8:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    9:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    10:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    11:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    12:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    13:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    14:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    15:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
}

perks_music = {
    1:	 ("Remove two -1 cards", (("-1", False, "None"), -2), False, False),
    2:	 ("Remove two -1 cards", (("-1", False, "None"), -2), False, False),
    3:	 ("Remove one -2 card", (("-2", False, "None"), -1), False, False),
    4:	 ("Replace two +1 cards with one +4 card", ((("+1", False, "None"), -2), (("+4", False, "None"), 1)), False, False),
    5:	 ("Replace two +1 cards with one +4 card", ((("+1", False, "None"), -2), (("+4", False, "None"), 1)), False, False),
    6:	 ("Replace one +0 card with one +1 Immobilize card", ((("+0", False, "None"), -1), (("+1", False, "Immobilize"), 1)), False, False),
    7:	 ("Replace one +0 card with one +1 Disarm card", ((("+0", False, "None"), -1), (("+1", False, "Disarm"), 1)), False, False),
    8:	 ("Replace one +0 card with one +2 Wound card", ((("+0", False, "None"), -1), (("+2", False, "Wound"), 1)), False, False),
    9:	 ("Replace one +0 card with one +2 Poison card", ((("+0", False, "None"), -1), (("+2", False, "Poison"), 1)), False, False),
    10:	 ("Replace one +0 card with one +2 Curse card", ((("+0", False, "None"), -1), (("+2", False, "Curse"), 1)), False, False),
    11:	 ("Replace one +0 card with one +3 Muddle card", ((("+0", False, "None"), -1), (("+3", False, "Muddle"), 1)), False, False),
    12:	 ("Replace one -1 card with one +0 Stun card", ((("-1", False, "None"), -1), (("+0", False, "Stun"), 1)), False, False),
    13:	 ("Add three [rolling] +1 cards", (("+1", True, "None"), 3), False, False),
    14:	 ("Add two [rolling] Curse cards", (("+0", True, "Curse"), 2), False, False),
    15:	 ("Add two [rolling] Curse cards", (("+0", True, "Curse"), 2), False, True),
}

perks_spiky = {
    1:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    2:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    3:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    4:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    5:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    6:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    7:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    8:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    9:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    10:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    11:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    12:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    13:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    14:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    15:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
}

perks_saw = {
    1:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    2:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    3:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    4:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    5:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    6:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    7:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    8:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    9:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    10:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    11:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    12:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    13:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    14:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    15:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
}

perks_triforce = {
    1:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    2:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    3:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    4:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    5:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    6:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    7:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    8:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    9:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    10:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    11:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    12:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    13:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    14:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    15:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
}

perks_buddies = {
    1:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    2:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    3:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    4:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    5:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    6:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    7:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    8:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    9:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    10:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    11:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    12:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    13:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    14:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
    15:	 ("[Unknown]", (("+0", False, "None"), 0), False, False),
}

class_master = {
    "Trispike":	("Brute", "Inox", perks_trispike, 0, 42),
    "Gear":	("Tinker", "Quatryl", perks_gear, 0, 43),
    "Star":	("Spellweaver", "Orchid", perks_star, 0, 44),
    "Daggers": ("Scoundrel", "Human", perks_daggers, 0, 45),
    "Shatter": ("Cragheart", "Savvas", perks_shatter, 0, 46),
    "Brain": ("Mindthief", "Vermling", perks_brain, 0, 47),
    "Sun": ("Sunkeeper", "Valrath", perks_sun, 31, 48),
    "Spears": ("Quartermaster", "Valrath", perks_spears, 32, 49),
    "Circles": ("[Unknown]", "[Unknown]", perks_circles, 33, 50),
    "Eclipse": ("[Unknown]", "[Unknown]", perks_eclipse, 34, 51),
    "Cthulu": ("[Unknown]", "[Unknown]", perks_cthulu, 35, 52),
    "Lightning": ("[Unknown]", "[Unknown]", perks_lightning, 36, 53),
    "Music": ("Soothsinger", "Quatryl", perks_music, 37, 54),
    "Spiky": ("[Unknown]", "[Unknown]", perks_spiky, 38, 55),
    "Saw": ("[Unknown]", "[Unknown]", perks_saw, 39, 56),
    "Triforce": ("[Unknown]", "[Unknown]", perks_triforce, 40, 57),
    "Buddies": ("[Unknown]", "[Unknown]", perks_buddies, 41, 58)
}

retire_quests = {
    "A Helping Hand":	("Experience two other characters meeting Retire reqs.", class_master["Music"]),
    "A Study of Anatomy":	("Experience other party members become exhausted 15 times.", class_master["Saw"]),
    "Aberrant Slayer":	("Kill at least one of each 'Demon' monster.", class_master["Triforce"]),
    "Augmented Abilities":	("Purchase four enhancements.", class_master["Circles"]),
    "Battle Legend":	("Gain 15 check marks from completed battle goals.", class_master["Music"]),
    "Elemental Samples":	("Complete one scenario from each group: GH: 8, 11, 12, 17, 18, 23, 26, 31, 35, 36, 37, 47, 50, 51, 52, 57, 58, 60, 64, 66, 70, 74, 77, 78, 83, 86, 87, 88, 89, 92, 93, DF: 3, 28, 29, 38, 43, 44, 48, 55, 56, 59, 81, 91, LS: 19, 32, 45, 49, 61, 62, 68, 79, WM: 9, 13, 63, 65, 73, 76, 80, 82, 85, CM: 7, 14, 15, 16, 24, 25, 33, 34, 39, 40, 41, 42, 46, 54, 66, 84, MS: 17, 30, 37, 47, 64, 70, 74, 93", class_master["Triforce"]),
    "Eternal Wanderer":	("Complete 15 scenarios.", class_master["Circles"]),
    "Fearless Stand":	("Kill 20 elite monsters.", class_master["Buddies"]),
    "Finding the Cure":	("1. Kill eight Forest Imps. (Unlocks scenario 59.), 2. Complete scenario 59 and any related scenarios.", misc_unlocks["Envelope_X"]),
    "Goliath Toppler":	("Complete 4 boss scenarios", class_master["Spiky"]),
    "Greed is Good":	("Have 200 GP in your possession.", class_master["Spears"]),
    "Implement of Light":	("Find Skullbane Axe. Use Skullbane Axe to kill 7 'Living' type monsters.", class_master["Sun"]),
    "Law Bringer":	("Kill 20 Bandits or Cultists.", class_master["Sun"]),
    "Merchant Class":	("Own at least the noted quantities of the following items: Head, Body, & Feet: 2 each, Hands (1 or 2): 3, Items: 4", class_master["Spears"]),
    "Piety in All Things":	("Donate 120 gold to the Sanctuary of the Great Oak.", class_master["Saw"]),
    "Pounds of Flesh":	("Kill 15 Vermlings.", class_master["Lightning"]),
    "Seeker of Xorn":	("1. Complete 3 'Crypt' scenarios. (Unlocks scenario 52), 2. Complete scenario 52 and any related scenarios.", class_master["Cthulu"]),
    "Take Back the Trees":	("1. Complete three scenarios from the following list: 3, 28, 29, 38, 43, 44, 48, 56, 59, 81, 91. (Unlocks scenario 55.), 2. Complete scenario 55 and any related scenarios.", class_master["Spiky"]),
    "The Fall of Man":	("1. Complete two scenarios from the following list: 19, 32, 45, 49, 61, 62, 68, 79 (Unlocks scenario 61.), 2. Complete scenario 61 and any related scenarios.", class_master["Eclipse"]),
    "The Perfect Poison":	("Kill at least three of each: Ooze, Lurker, Spitting Drake", class_master["Cthulu"]),
    "The Thin Places":	("Complete 6 side scenarios. (Scene # > 51).", class_master["Eclipse"]),
    "Trophy Hunt":	("Kill 20 different types of monsters.", class_master["Buddies"]),
    "Vengeance":	("1. Complete 4 scenarios connected to Gloomhaven. (Unlocks scenario 57.), 2. Complete scenario 57 and any related scenarios.", misc_unlocks["Envelope_X"]),
    "Zealot of the Blood God":	("Become exhausted 12 times.", class_master["Lightning"])
}


class Reference:
    """Stores all immutable information regarding the game."""

    def __init__(self):

        self.global_achievements = misc_data["global_achieves"]
        self.party_achievements = misc_data["party_achieves"]
        # self.donation_influence = misc_data["donation_influence"]
        self.donation_landmarks = misc_data["donation_landmarks"]
        self.prosperity_landmarks = misc_data["prosperity_levels"]

        self.monster_names = misc_data["monster_names"]
        self.boss_names = misc_data["boss_names"]

        self.xp_to_level = misc_data["level_up_xp"]
        self.starting_attack_deck = misc_data["default_deck"]
        self.classes = class_master
        self.retire = retire_quests

        self.items = items_master
        self.random_item_designs = misc_data["random_designs"]
        self.reputation_modifiers = misc_data["reputation_mod"]
        self.reputation_thresholds = misc_data["reputation_threshold"]

        self.misc_unlocks = misc_unlocks

        self.locations = locations_master
        self.location_chests = chest_contents
        self.random_scenarios = misc_data["random_scenes"]
        self.battle_goals = battle_goals
